apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: go-task
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/tasks?sslmode=disable
  JWT_SECRET: mysecret